# Generated by Django 2.2.17 on 2020-12-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_hjgjhg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bgfmhfm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jhgjhgj", models.BigIntegerField()),
                ("bcbvccbvc", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
