# Generated by Django 2.2.17 on 2020-12-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bgfmhfm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hjgjhg',
        ),
    ]
